"use client"
// Auto-generated by `npx boneyard-js build` — do not edit manually
// Run `pnpm bones` to regenerate with live pixel measurements
// This stub is committed so the build succeeds without bone data
